# 全局信息
title = "TOML读取成功"

# 应用信息
[app]
author = "付鹏篚"
info = "笔记"
mark = "第一行\n第二行."            # 换行
release = 2020-09-09              # 时间

[file]
LOG_ROUTER_PATH="./log/router"
LOG_ROUTER_NAME="routerLogFile"
LOG_DETAILS_PATH="./log/detials"
LOG_DETAILS_NAME="routerLogFile"

[jsonwebtoken]
jwtSecret="newbie"