# Toml 示例
title = "TOML Example"
[owner]
name = "newbie"
dob = 1979-05-27T07:32:00-08:00 # 日期是一等公民

[Mysql]
server = "127.0.0.1:3306"
connection_max = 200
dbname = "blog"
user = "root"
password = "root"
enabled = true
