info:
  contact: {}
paths:
  /FindUserByName:
    get:
      consumes:
      - application/json
      description: 根据用户名查询用户信息
      parameters:
      - description: 用户账户名
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 查询用户信息
      tags:
      - 用户接口
  /Login:
    post:
      consumes:
      - application/json
      description: 根据用户名查询用户信息
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200","data":""}'
          schema:
            type: string
      summary: 查询用户信息
      tags:
      - 用户接口
  /creatUser:
    put:
      consumes:
      - application/json
      description: 创建用户
      produces:
      - application/json
      responses: {}
      summary: 创建用户信息
      tags:
      - 用户接口
swagger: "2.0"
